
language: java

rvm:
  - 12

services:
  - postgresql

addons:
  - postgresql: '9.4'

before_script:
  - psql -c "create database db_myerp;" -U postgres
  - psql db_myerp < 01_create_schema.sql
  - psql db_myerp < 02_create_tables.sql
  - psql db_myerp < 21_insert_data_demo.sql

script:
  - mvn clean install -P test-business,test-consumer
